alias updatemaster="git checkout -b remake; git branch -D master; git fetch; git checkout master; git pull origin master"
alias updatemain="git checkout -b remake; git branch -D main; git fetch; git checkout main; git pull origin main"
alias cls="clear"
alias shell="code ~/Shell-Scripts"
alias reactpractice="code ~/Desktop/React-Practice"
