alias updatemaster="~/Shell-Scripts/common.sh/updatemaster.sh master"
alias updatemain="~/Shell-Scripts/common.sh/updatemaster.sh main"
alias cls="clear"
alias shell="code ~/Shell-Scripts"
alias reactpractice="code ~/Desktop/React-Practice"
alias src="source ~/.bashrc"
